import type { IconBaseProps, IconType } from "react-icons"
import {
  FiCalendar,
  FiCheck,
  FiChevronDown,
  FiChevronLeft,
  FiChevronRight,
  FiChevronUp,
  FiChevronsDown,
  FiChevronsUp,
  FiClock,
  FiEdit2,
  FiList,
  FiMaximize2,
  FiMinus,
  FiMove,
  FiPause,
  FiPlay,
  FiPlus,
  FiSettings,
  FiTrash2,
  FiX,
} from "react-icons/fi"
import { LuFlame } from "react-icons/lu"

export type AppIconProps = IconBaseProps
export type AppIcon = IconType

export const icons = {
  calendar: FiCalendar,
  clock: FiClock,
  play: FiPlay,
  pause: FiPause,
  check: FiCheck,
  plus: FiPlus,
  minus: FiMinus,
  settings: FiSettings,
  close: FiX,
  grip: FiMove,
  chevronUp: FiChevronUp,
  chevronDown: FiChevronDown,
  chevronLeft: FiChevronLeft,
  chevronRight: FiChevronRight,
  chevronsUp: FiChevronsUp,
  chevronsDown: FiChevronsDown,
  list: FiList,
  expand: FiMaximize2,
  edit: FiEdit2,
  trash: FiTrash2,
  flame: LuFlame,
} satisfies Record<string, AppIcon>

export const {
  calendar: CalendarIcon,
  clock: ClockIcon,
  play: PlayIcon,
  pause: PauseIcon,
  check: CheckIcon,
  plus: PlusIcon,
  minus: MinusIcon,
  settings: SettingsIcon,
  close: CloseIcon,
  grip: GripIcon,
  chevronUp: ChevronUpIcon,
  chevronDown: ChevronDownIcon,
  chevronLeft: ChevronLeftIcon,
  chevronRight: ChevronRightIcon,
  chevronsUp: ChevronsUpIcon,
  chevronsDown: ChevronsDownIcon,
  list: ListIcon,
  expand: ExpandIcon,
  edit: EditIcon,
  trash: TrashIcon,
  flame: FlameIcon,
} = icons
